---
- name: Main Playbook
  hosts: all
  become: yes
  gather_facts: true

  tasks:
    - name: Include secret variables
      include_vars:
        file: vars/secrets.yml
  
  roles:
    - common

- import_playbook: webserver.yml
- import_playbook: backup.yml
- import_playbook: download.yml