testing:
  hosts:
    server1:
      ansible_host: 192.168.1.6
      ansible_user: kangketik
      ansible_port: 22
    server2:
      ansible_host: 192.168.1.7
      ansible_user: kangketik
      ansible_port: 22
    server3:
      ansible_host: 192.168.1.8
      ansible_user: kangketik
      ansible_port: 22
