---
# vars file for roles/webserver

repository_name: "webserver"
repository_branch: "main"
repository_url: "git@github.com:kangketikonlen/webserver.git"
repository_folder_dest: "/home/{{ ansible_user }}/docker/webserver"
repository_private_key: "/home/{{ ansible_user }}/.ssh/github_private"
